apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-brain-data
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.brainData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bot-db
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.botDb }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bot-home
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.botHome }}
